### ISSUE TITLE
weblate/weblate:4.5.1-1 ImportError: libmariadb.so.3: cannot open shared object file

### ISSUE THREAD

**Issue by brezerk** [WeblateOrg/docker#1008]
**Describe the issue**

Unable to start weblate/weblate:4.5.1-1 image with mariadb-10.5 support:

```
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: libmariadb.so.3: cannot open shared object file: No such file or directory
```

Seems like `libmariadb3` package is missing;

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Deploy mariadb
2. Deploy weblate wit configuration override: 
```
configOverride: |

  DATABASES = { 
    "default": {
        # Database engine
        "ENGINE": "django.db.backends.mysql",
        # Database name
        "NAME": "weblate",
        # Database user
        "USER": "weblate",
        # Database password
        "PASSWORD": "xxxxxxxxxxxxx",
        # Set to empty string for localhost
        "HOST": "xxx.xxx.xxx.xxx",
        # Set to empty string for default
        "PORT": "3306",
        # In case you wish to use additional
        # connection options
        "OPTIONS": {}, 
    }
  }

```
3. Start weblate;

**Expected behavior**

Everything works

**Screenshots**

**Exception traceback**

```
[2021-03-18 21:13:01,438: WARNING/107] Handled exception: NameError: name '_mysql' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: libmariadb.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 34, in main
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.7/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.7/dist-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/dist-packages/weblate/addons/models.py", line 42, in <module>
    from weblate.trans.models import Component, Unit
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/__init__.py", line 25, in <module>
    from weblate.trans.models.agreement import ContributorAgreement
  File "/usr/local/lib/python3.7/dist-packages/weblate/trans/models/agreement.py", line 42, in <module>
    class ContributorAgreement(models.Model):
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 122, in __new__
    new_class.add_to_class('_meta', Options(meta, app_label))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 326, in add_to_class
    value.contribute_to_class(cls, name)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/options.py", line 206, in contribute_to_class
    self.db_table = truncate_name(self.db_table, connection.ops.max_name_length())
  File "/usr/local/lib/python3.7/dist-packages/django/db/__init__.py", line 28, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 214, in __getitem__
    backend = load_backend(db['ENGINE'])
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/mysql/base.py", line 15, in <module>
    import MySQLdb as Database
  File "/usr/local/lib/python3.7/dist-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
```

**Additional context**

**Comment by brezerk** [comment]
Seems like `mysqlclient>=2.0.1` defined at https://github.com/WeblateOrg/weblate/blob/master/requirements-optional.txt#L21 is missing at https://github.com/WeblateOrg/docker/blob/master/requirements.txt

**Comment by nijel** [comment]
The latter is only used to pin specific versions of the dependencies to make the build more reproducible, If you think mysqlclient should be there, feel free to submit a pull request.
