### ISSUE TITLE
DB insert error at startup

### ISSUE THREAD

**Issue by pleonex** [WeblateOrg/docker#105]
When I start weblate with a docker container I see the following errors at startup. In version 3.3 the errors happens in a loop.

```
weblate_1   | Postgres is up
weblate_1   | Operations to perform:                                                                                                                                                    [0/1899]
weblate_1   |   Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth,
 wladmin
weblate_1   | Running migrations:
weblate_1   |   No migrations to apply.
weblate_1   | ERROR Handled exception error: cannot add item to database
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 111, in __getitem__
weblate_1   |     value = self.cache[key]
weblate_1   | KeyError: 'entries'
weblate_1   |
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 515, in _create_schedule
weblate_1   |     self._store[str('entries')]
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 113, in __getitem__
weblate_1   |     f = BytesIO(self.dict[key.encode(self.keyencoding)])
weblate_1   | KeyError: b'entries'
weblate_1   |
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 11, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/runner.py", line 34, in main
weblate_1   |     execute_from_command_line(argv)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 316, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 353, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 35, in handle
weblate_1   |     app=app
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 458, in __init__
weblate_1   |     Scheduler.__init__(self, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 225, in __init__
weblate_1   |     self.setup_schedule()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 486, in setup_schedule
weblate_1   |     self._create_schedule()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 519, in _create_schedule
weblate_1   |     self._store[str('entries')] = {}
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
weblate_1   |     self.dict[key.encode(self.keyencoding)] = f.getvalue()
weblate_1   | _dbm.error: cannot add item to database
weblate_1   | Exception ignored in: <bound method Shelf.__del__ of <shelve.DbfilenameShelf object at 0x7f0f3f198908>>
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 162, in __del__
weblate_1   |     self.close()
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 144, in close
weblate_1   |     self.sync()
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 168, in sync
weblate_1   |     self[key] = entry
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
weblate_1   |     self.dict[key.encode(self.keyencoding)] = f.getvalue()
weblate_1   | _dbm.error: cannot add item to database
```

**Comment by pleonex** [comment]
**Update**: I revered to 3.2.2-5 with a backup I did before the upgrade and I also see the same error at startup. The difference is that it only happens once and the site runs fine after it. I didn't notice it before. With 3.3 the error happens in a loop and the site doesn't seem to start.

**Comment by nijel** [comment]
Hmm, https://github.com/WeblateOrg/docker/commit/f9be2d23f96711f47b789290a2c79f718869203f was supposed to address this. The problem is that Celery sometimes corrupts it's scheduling database, see https://github.com/WeblateOrg/docker/issues/102#issuecomment-443453543

**Comment by nijel** [comment]
Yes, that is supposed to work, can you please post traceback you get in that case? It should be at least slightly different.

**Comment by pleonex** [comment]
Here it's the traceback:
```
pleonex@vpsXXXXXX:/weblate/docker$ docker-compose run --rm weblate cleanup_celery                                                                                                                                                    [23/162]
Starting docker_cache_1    ... done
Starting docker_database_1 ... done
Postgres is up
ERROR Handled exception error: cannot add item to database
Traceback (most recent call last):
  File "/usr/lib/python3.6/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 515, in _create_schedule
    self._store[str('entries')]
  File "/usr/lib/python3.6/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
KeyError: b'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 35, in handle
    app=app
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 458, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 225, in __init__
    self.setup_schedule()
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 486, in setup_schedule
    self._create_schedule()
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 519, in _create_schedule
    self._store[str('entries')] = {}
  File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database
Exception ignored in: <bound method Shelf.__del__ of <shelve.DbfilenameShelf object at 0x7f4c918bdcc0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/shelve.py", line 162, in __del__
    self.close()
  File "/usr/lib/python3.6/shelve.py", line 144, in close
    self.sync()
  File "/usr/lib/python3.6/shelve.py", line 168, in sync
    self[key] = entry
  File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database
```

Let me know if you need more information or anything to try :)

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed, it would be great if you can verify the fix.

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by ToxicTree** [comment]
Saw this post but we still have problems. Can we select a different version to use in docker-compose that has the right dependencies or is there anything else we can do?

This is what we get after running `docker-compose run --rm weblate cleanup_celery`:
```
ERROR Handled exception TypeError: unsupported format string passed to error.__format__
Traceback (most recent call last):
  File "/usr/lib/python3.6/shelve.py", line 111, in __getitem__
    value = self.cache[key]
KeyError: 'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 515, in _create_schedule
    self._store[str('entries')]
  File "/usr/lib/python3.6/shelve.py", line 113, in __getitem__
    f = BytesIO(self.dict[key.encode(self.keyencoding)])
KeyError: b'entries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 36, in handle
    app=app
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 458, in __init__
    Scheduler.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 225, in __init__
    self.setup_schedule()
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 486, in setup_schedule
    self._create_schedule()
  File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 519, in _create_schedule
    self._store[str('entries')] = {}
  File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 41, in handle
    'Removing corrupted schedule file: {:r}'.format(error)
TypeError: unsupported format string passed to error.__format__
Exception ignored in: <bound method Shelf.__del__ of <shelve.DbfilenameShelf object at 0x7fb4fe39f198>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/shelve.py", line 162, in __del__
    self.close()
  File "/usr/lib/python3.6/shelve.py", line 144, in close
    self.sync()
  File "/usr/lib/python3.6/shelve.py", line 168, in sync
    self[key] = entry
  File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
    self.dict[key.encode(self.keyencoding)] = f.getvalue()
_dbm.error: cannot add item to database
```

### Original problem:

We are having problems with the docker image. We had to restart some containers a few weeks ago and noticed that weblate is restarting every 15 seconds while on, making it impossible to use the platform.
The installation was made **2018-11-08** with the guide on your homepage: https://docs.weblate.org/en/latest/admin/deployments.html#docker

This is the output we get every time the weblate container fails and restart:
```weblate_1   | Postgres is up
weblate_1   | Operations to perform:
weblate_1   |   Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
weblate_1   | Running migrations:
weblate_1   |   No migrations to apply.
weblate_1   | ERROR Handled exception TypeError: unsupported format string passed to error.__format__
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 111, in __getitem__
weblate_1   |     value = self.cache[key]
weblate_1   | KeyError: 'entries'
weblate_1   |
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 515, in _create_schedule
weblate_1   |     self._store[str('entries')]
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 113, in __getitem__
weblate_1   |     f = BytesIO(self.dict[key.encode(self.keyencoding)])
weblate_1   | KeyError: b'entries'
weblate_1   |
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 36, in handle
weblate_1   |     app=app
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 458, in __init__
weblate_1   |     Scheduler.__init__(self, *args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 225, in __init__
weblate_1   |     self.setup_schedule()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 486, in setup_schedule
weblate_1   |     self._create_schedule()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/celery/beat.py", line 519, in _create_schedule
weblate_1   |     self._store[str('entries')] = {}
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
weblate_1   |     self.dict[key.encode(self.keyencoding)] = f.getvalue()
weblate_1   | _dbm.error: cannot add item to database
weblate_1   |
weblate_1   | During handling of the above exception, another exception occurred:
weblate_1   |
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 11, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/runner.py", line 34, in main
weblate_1   |     execute_from_command_line(argv)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 316, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 353, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python3.6/dist-packages/weblate/utils/management/commands/cleanup_celery.py", line 41, in handle
weblate_1   |     'Removing corrupted schedule file: {:r}'.format(error)
weblate_1   | TypeError: unsupported format string passed to error.__format__
weblate_1   | Exception ignored in: <bound method Shelf.__del__ of <shelve.DbfilenameShelf object at 0x7f0e2f9d8c88>>
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 162, in __del__
weblate_1   |     self.close()
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 144, in close
weblate_1   |     self.sync()
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 168, in sync
weblate_1   |     self[key] = entry
weblate_1   |   File "/usr/lib/python3.6/shelve.py", line 125, in __setitem__
weblate_1   |     self.dict[key.encode(self.keyencoding)] = f.getvalue()
weblate_1   | _dbm.error: cannot add item to database
weblatedocker_weblate_1 exited with code 1
```

Configuration: (docker-compose.yml)
```version: '3.1'
services:
  weblate:
    image: weblate/weblate
    ports:
      - 8011:80
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:9.6-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:4-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```


Versions: (docker-compose run --rm weblate list_versions)
``` * Weblate 3.4
 * Python 3.6.7
 * Django 2.1.5
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.7.5
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.13.0-46-generic (x86_64)```

**Comment by nijel** [comment]
You can update to latest Weblate image by `docker-compose pull`.

**Comment by ToxicTree** [comment]
Thank you for the reply. We still have the same issues after `docker-compose pull`

```
Pulling cache (redis:4-alpine)...
4-alpine: Pulling from library/redis
Digest: sha256:ee1145f51f3f5e9fd79d01772169ed0dc833220f28cc8675490bfd54866f56be
Status: Image is up to date for redis:4-alpine
Pulling database (postgres:9.6-alpine)...
9.6-alpine: Pulling from library/postgres
Digest: sha256:215ad1cb0084e32ef2648394f8d08c9cfa29a86371ebe9e4c88b0dd51aa0bfdc
Status: Image is up to date for postgres:9.6-alpine
Pulling weblate (weblate/weblate:latest)...
latest: Pulling from weblate/weblate
Digest: sha256:a5ed143633716328e68664e3176e3e3d4732adeb7baecdbd5df10b993e45e815
Status: Image is up to date for weblate/weblate:latest
```

Can we specify another image than "weblate:latest"?

**Comment by ToxicTree** [comment]
More info:

```
 * Weblate 3.4
 * Python 3.6.7
 * Django 2.1.7
 * Celery 4.2.1
 * celery-batches 0.2
 * six 1.12.0
 * social-auth-core 3.0.0
 * social-auth-app-django 3.1.0
 * django-appconf 1.0.2
 * translate-toolkit 2.3.1
 * translation-finder 1.0
 * Whoosh 2.7.4
 * defusedxml 0.5.0
 * Git 2.17.1
 * Pillow 5.1.0
 * python-dateutil 2.8.0
 * lxml 4.2.1
 * django-crispy-forms 1.7.2
 * django_compressor 2.2
 * djangorestframework 3.9.1
 * user-agents 1.1.0
 * jellyfish 0.7.1
 * diff-match-patch 20121119
 * pytz 2018.9
 * pyuca 1.2
 * PyYAML 3.12
 * tesserocr 2.4.0
 * Mercurial 4.5.3
 * git-svn 2.17.1
 * Database backends: django.db.backends.postgresql
 * Cache backends: avatar:FileBasedCache, default:RedisCache
 * Celery: redis://cache:6379/1, redis://cache:6379/1, regular
 * Platform: Linux 4.13.0-46-generic (x86_64)
```

**Comment by ToxicTree** [comment]
Ok, I just found out how to change the version of weblate.
In the docker-compose.yml file, define the version tag `weblate/weblate:3.2.2-5`

```
version: '3'
services:
  weblate:
    image: weblate/weblate:3.2.2-5
    ports:
      - 8011:80
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    restart: always
    depends_on:
      - database
      - cache
  database:
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  cache:
    image: redis:4-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```

We can use weblate again!

**Comment by nijel** [comment]
Oops, there was bug in the cleanup code and because it is in the exception handling it was a bit hidden in the message you posted. I've just fixed this by https://github.com/WeblateOrg/weblate/commit/af84fd2c8130a4692f7d5fcc104779952026568c for upcoming 3.5 release (scheduled on this Sunday).
