### ISSUE TITLE
weblate/weblate-4.8.1-2

### ISSUE THREAD

**Issue by brezerk** [WeblateOrg/docker#1222]
**Describe the issue**

Hi. Thank you for your awesome software.

There seems to be an issue with `4.8.1-2` image: siple tag update from `4.8-1` to `4.8.1-2` (**note**: i am using arm64 arch) reuslts into startup error:

```
SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
```

Reverting tag back to `4.8-1` or more recent works as expected;

**I already tried**

Describe the steps you tried to solve the problem yourself.

- [x] I've read and searched [the docs](https://docs.weblate.org/) and did not find the answer there.
      If you didn’t try already, try to search there what you wrote above.

**To Reproduce the issue**

1. Edit deployment and set image tag to `4.8.1-2`
2. Wait for new pod to startup;
3. Observe startup errors;

**Expected behavior**

- Container is in runnig status;

**Screenshots**

**Exception traceback**

```
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/weblate/runner.py", line 34, in main
    utility.execute()
  File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.9/dist-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/dist-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.9/dist-packages/django/apps/config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/weblate/accounts/models.py", line 42, in <module>
    from weblate.accounts.data import create_default_notifications
  File "/usr/local/lib/python3.9/dist-packages/weblate/accounts/data.py", line 21, in <module>
    from weblate.accounts.notifications import FREQ_INSTANT, SCOPE_ADMIN, SCOPE_WATCHED
  File "/usr/local/lib/python3.9/dist-packages/weblate/accounts/notifications.py", line 41, in <module>
    from weblate.utils.markdown import get_mention_users
  File "/usr/local/lib/python3.9/dist-packages/weblate/utils/markdown.py", line 24, in <module>
    import misaka
  File "/usr/local/lib/python3.9/dist-packages/misaka/__init__.py", line 3, in <module>
    from .api import *
  File "/usr/local/lib/python3.9/dist-packages/misaka/api.py", line 10, in <module>
    from .callbacks import python_callbacks, to_string
  File "/usr/local/lib/python3.9/dist-packages/misaka/callbacks.py", line 10, in <module>
    def cb_blockcode(ob, text, lang, data):
SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)
```

**Additional context**

**Comment by nijel** [comment]
Seems like cffi binary wheel package is incompatible with Debian bullseye libcffi. We should build it from the source instead.
