### ISSUE TITLE
permission denied /run/celerybeat.pid

### ISSUE THREAD

**Issue by paulpach** [WeblateOrg/docker#124]
I am running edge,  created just now,   When the docker container starts,  it shows this in the log:

```cs
Mon Feb  4 12:46:11 2019 - dropping root privileges after application loading
Mon Feb  4 12:46:11 2019 - *** uWSGI is running in multiple interpreter mode ***
Mon Feb  4 12:46:11 2019 - spawned uWSGI master process (pid: 126)
Mon Feb  4 12:46:11 2019 - spawned uWSGI worker 1 (pid: 179, cores: 1)
Mon Feb  4 12:46:11 2019 - spawned uWSGI worker 2 (pid: 180, cores: 1)
Mon Feb  4 12:46:11 2019 - spawned uWSGI worker 3 (pid: 181, cores: 1)
Mon Feb  4 12:46:11 2019 - spawned uWSGI worker 4 (pid: 182, cores: 1)
Mon Feb  4 12:46:11 2019 - spawned uWSGI worker 5 (pid: 183, cores: 1)
Mon Feb  4 12:46:11 2019 - spawned uWSGI worker 6 (pid: 184, cores: 1)
Mon Feb  4 12:46:11 2019 - *** Stats server enabled on :1717 fd: 20 ***
celery beat v4.2.1 (windowlicker) is starting.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/celery/platforms.py", line 148, in acquire
    self.write_pid()
  File "/usr/local/lib/python3.6/dist-packages/celery/platforms.py", line 211, in write_pid
    pidfile_fd = os.open(self.path, PIDFILE_FLAGS, PIDFILE_MODE)
PermissionError: [Errno 13] Permission denied: '/run/celerybeat.pid'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/celery", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/celery/__main__.py", line 16, in main
    _main()
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 322, in main
    cmd.execute_from_commandline(argv)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 275, in execute_from_commandline
    return self.handle_argv(self.prog_name, argv[1:])
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 488, in handle_argv
    return self.execute(command, argv)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/celery.py", line 420, in execute
    ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 279, in run_from_argv
    sys.argv if argv is None else argv, command)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 363, in handle_argv
    return self(*args, **options)
  File "/usr/local/lib/python3.6/dist-packages/celery/bin/base.py", line 238, in __call__
```

I remote into my container and I can see the permissions for /run:
```sh
# ls -ld /run
drwxr-xr-x 1 root root 4096 Feb  4 12:45 /run
```

**Comment by nijel** [comment]
Indeed edge is broken right now, I started some changes, but could not complete them and it stayed in broken state, sorry.

**Comment by nijel** [comment]
Thank you for your report, the issue you have reported has just been fixed. 

* In case you see problem with the fix, please comment on this issue. 
* In case you see similar problem, please open separate issue.
* If you are happy with the outcome, consider supporting Weblate by [donating](https://weblate.org/donate/).

**Comment by malonr** [comment]
How did you solve it?
