### ISSUE TITLE
Migration issues upgrading existing Weblate installation to latest Docker tag

### ISSUE THREAD

**Issue by TheAssassin** [WeblateOrg/docker#1314]
### Describe the issue

I auto upgrade many Docker-installed services regularly using a script, with Weblate being one of them. As of (at least) yesterday, Weblate has been down (similar symptoms as in issue as in #1313) due to a migrations issue. 

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior

Upgrade an existing Weblate instance to the latest Docker tag.

I have not (yet) tried to reproduce this on a vanilla installation.

### Expected behavior

```
docker-compose pull
docker-compose up -d
```

results in a working, updated Weblate instance.

### Exception traceback

```pytb
Log excerpt:


> docker-compose logs -f weblate
Attaching to weblate-docker_weblate_1
weblate_1   | Starting...
weblate_1   | Postgres is up
weblate_1   | [2021-12-19 15:08:44,199: WARNING/27] Handled exception: ProgrammingError: column c.relispartition does not exist
weblate_1   | LINE 3:             CASE WHEN c.relispartition THEN 'p' WHEN c.relki...
weblate_1   |                               ^
weblate_1   | 
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 83, in _execute
weblate_1   |     return self.cursor.execute(sql)
weblate_1   | psycopg2.errors.UndefinedColumn: column c.relispartition does not exist
weblate_1   | LINE 3:             CASE WHEN c.relispartition THEN 'p' WHEN c.relki...
weblate_1   |                               ^
weblate_1   | 
weblate_1   | 
weblate_1   | The above exception was the direct cause of the following exception:
weblate_1   | 
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/weblate/runner.py", line 34, in main
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/__init__.py", line 419, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 373, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/base.py", line 417, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/showmigrations.py", line 54, in handle
weblate_1   |     return self.show_plan(connection, options['app_label'])
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/core/management/commands/showmigrations.py", line 121, in show_plan
weblate_1   |     loader = MigrationLoader(connection)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/loader.py", line 53, in __init__
weblate_1   |     self.build_graph()
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/loader.py", line 223, in build_graph
weblate_1   |     self.applied_migrations = recorder.applied_migrations()
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
weblate_1   |     if self.has_table():
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/migrations/recorder.py", line 56, in has_table
weblate_1   |     tables = self.connection.introspection.table_names(cursor)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/base/introspection.py", line 52, in table_names
weblate_1   |     return get_names(cursor)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/base/introspection.py", line 47, in get_names
weblate_1   |     return sorted(ti.name for ti in self.get_table_list(cursor)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/postgresql/introspection.py", line 49, in get_table_list
weblate_1   |     cursor.execute("""
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 67, in execute
weblate_1   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
weblate_1   |     return executor(sql, params, many, context)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 85, in _execute
weblate_1   |     return self.cursor.execute(sql, params)
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/utils.py", line 90, in __exit__
weblate_1   |     raise dj_exc_value.with_traceback(traceback) from exc_value
weblate_1   |   File "/usr/local/lib/python3.9/dist-packages/django/db/backends/utils.py", line 83, in _execute
weblate_1   |     return self.cursor.execute(sql)
weblate_1   | django.db.utils.ProgrammingError: column c.relispartition does not exist
weblate_1   | LINE 3:             CASE WHEN c.relispartition THEN 'p' WHEN c.relki...
weblate_1   |                               ^
weblate_1   | 
weblate_1   | 
weblate_1   | Database migration has failed. Please check the error message above.
weblate_1   | In case you are upgrading from an 3.x version, please upgrade to 4.1.1-3 first.
```
```


### Additional context

I assume I've upgraded from `weblate/weblate:4.9-1`, because that version apparently still works. This is good, because that means data has not been corrupted.

I'm not entirely sure why this issue has started to arise. I suspect a combination of psycopg2 and Postgres that doesn't work. The Docker setup apparently uses Postgres 13. I have no idea what that attribute's job is, a fix regarding it is mentioned in a changelog https://www.postgresql.org/docs/12/release-12-1.html.

The Postgres version has not changed in a while as far as I can see:

```
7601ceb1 (Michal Čihař      2020-10-05 15:22:52 +0200 18)     image: postgres:13-alpine
```

Docker images:

```
postgres                                         13-alpine           c010012afcb2   2 weeks ago     205MB
weblate/weblate                                  4.10-1              93fddc7b4839   40 hours ago    837MB
weblate/weblate                                  latest              93fddc7b4839   40 hours ago    837MB
weblate/weblate                                  <none>              a5de22ed7381   4 weeks ago     836MB
weblate/weblate                                  4.9-1               0f4a62ef296b   5 weeks ago     835MB
```

(I had pulled 4.9-1 manually to test against, I could probably have used `a5de22ed7381` instead)

**Comment by nijel** [comment]
Strange, `postgres:13-alpine` is what we use in our CI pipeline, and it works fine there.

Are you sure you are using that image? According to PostgreSQL documentation, this field was added in PostgreSQL 10. And that's what was changed as well, they have [dropped support for 9.6](https://docs.djangoproject.com/en/4.0/releases/4.0/#dropped-support-for-postgresql-9-6).

So to me, it seems like you are still running PostgreSQL 9.6, which is no longer supported by the container. Still, this should have been documented somewhere...

**Comment by TheAssassin** [comment]
Well, I'm using the off-the-shelf docker-compose file. I've kept upgrading the Git repository and Docker images for over a year now, the chance from Postgres 9.6 to 13 was made over a year. Your guess is exactly right:

```
> docker inspect weblate-docker_database_1 | ag image
        "Image": "sha256:7526db3fb03b222c565e7ce90c3d839d904c7135e84220b29dddfd73867f125e",
            "Image": "postgres:9-alpine",
```

I'll try to figure out where _that_ is configured...

**Comment by TheAssassin** [comment]
Turns out there's a `docker-override.yml` in which I apparently fixed the Postgres version. I think I remember some compatibility issues over a year ago. In the meantime, Weblate has dropped support for 9, which is fine, and it's good it's documented now. I'll upgrade the Postgres container to 13 and will report back how that's going to work.

Thanks for the hint!

**Comment by nijel** [comment]
Upgrading PostgreSQL in Docker is unfortunately not that straightforward, so that might be the reason why you've fixed the version. https://github.com/docker-library/postgres/issues/37 mentions several approaches how to do that.

**Comment by TheAssassin** [comment]
I've done it before. I think the issue was that the chosen Postgres was too new for Weblate or something like that. I really don't remember. I'll figure it out, thanks.

**Comment by romanr** [comment]
> Update: it's working now. What a weird issue to debug. Thanks again!

Can you share please how did you solve it?

**Comment by TheAssassin** [comment]
As pointed out in https://github.com/WeblateOrg/docker/issues/1314#issuecomment-997930467, I had to upgrade Postgres to a newer version.
