### ISSUE TITLE
Migration fails from Weblate 4.10.1-1 to 4.11.2-1

### ISSUE THREAD

**Issue by sfranken-smartwireless** [WeblateOrg/docker#1454]
### Describe the issue

After upgrading Weblate Docker container form 4.10.1-1 to 4.11.2-1 migration 0021_migrate_internal_groups.py fails.

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Expected behavior

Migrations are successful.

### Exception traceback

```pytb
weblate_1   | Postgres 140002 is up
weblate_1   | Starting database migration...
weblate_1   | Operations to perform:
weblate_1   |   Apply all migrations: accounts, addons, admin, auth, authtoken, checks, configuration, contenttypes, fonts, gitexport, glossary, lang, memory, metrics, screenshots, sessions, social_django, trans, utils, vcs, weblate_auth, wladmin
weblate_1   | Running migrations:
weblate_1   |   Applying weblate_auth.0021_migrate_internal_groups...[2022-04-04 11:32:05,844: WARNING/44] Handled exception: ValueError: Internal group SmartConnect@VCS has more than one project assigned!
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/weblate/runner.py", line 34, in main
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/core/management/__init__.py", line 440, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 414, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 460, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/core/management/base.py", line 98, in wrapped
weblate_1   |     res = handle_func(*args, **kwargs)
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 290, in handle
weblate_1   |     post_migrate_state = executor.migrate(
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 131, in migrate
weblate_1   |     state = self._migrate_all_forwards(
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 163, in _migrate_all_forwards
weblate_1   |     state = self.apply_migration(
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 248, in apply_migration
weblate_1   |     state = migration.apply(state, schema_editor)
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 131, in apply
weblate_1   |     operation.database_forwards(
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
weblate_1   |     self.code(from_state.apps, schema_editor)
weblate_1   |   File "/usr/local/lib/python3.10/site-packages/weblate/auth/migrations/0021_migrate_internal_groups.py", line 18, in migrate_internal_groups
weblate_1   |     raise ValueError(
weblate_1   | ValueError: Internal group SmartConnect@VCS has more than one project assigned!
```

**Comment by nijel** [comment]
You've probably made some modifications to Weblate internal groups, and the migration does not deal with that. Please fix the project assignment for the `SmartConnect@VCS` group manually before doing the migration.
