### ISSUE TITLE
Docker container fails with middleware error

### ISSUE THREAD

**Issue by wichert** [WeblateOrg/docker#153]
**Describe the bug**

I am trying to deploy the `weblate/weblate:3.4-4` docker container on AWS. Trying to start the container always results in this error:

```
django.core.exceptions.ImproperlyConfigured: CSRF_USE_SESSIONS is enabled, but request.session is not set. SessionMiddleware must appear before CsrfViewMiddleware in MIDDLEWARE.
```

<details>
<summary>Complete traceback</summary>

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/usr/local/lib/python3.6/dist-packages/django/utils/deprecation.py", line 90, in __call__
response = self.process_request(request)
File "/usr/local/lib/python3.6/dist-packages/django/middleware/security.py", line 25, in process_request
host = self.redirect_host or request.get_host()
File "/usr/local/lib/python3.6/dist-packages/django/http/request.py", line 106, in get_host
raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '10.180.28.95:32804'. You may need to add '10.180.28.95' to ALLOWED_HOSTS.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/django/middleware/csrf.py", line 162, in _get_token
return request.session.get(CSRF_SESSION_KEY)
AttributeError: 'WSGIRequest' object has no attribute 'session'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/exception.py", line 108, in get_exception_response
response = callback(request, **{**param_dict, 'exception': exception})
File "/usr/local/lib/python3.6/dist-packages/django/utils/decorators.py", line 134, in _wrapped_view
result = middleware.process_request(request)
File "/usr/local/lib/python3.6/dist-packages/django/middleware/csrf.py", line 200, in process_request
csrf_token = self._get_token(request)
File "/usr/local/lib/python3.6/dist-packages/django/middleware/csrf.py", line 167, in _get_token
'in MIDDLEWARE%s.' % ('_CLASSES' if settings.MIDDLEWARE is None else '')
django.core.exceptions.ImproperlyConfigured: CSRF_USE_SESSIONS is enabled, but request.session is not set. SessionMiddleware must appear before CsrfViewMiddleware in MIDDLEWARE.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/weblate/trans/views/basic.py", line 319, in server_error
status=500,
File "/usr/local/lib/python3.6/dist-packages/weblate/trans/util.py", line 257, in render
return django_render(request, template, context, status=status)
File "/usr/local/lib/python3.6/dist-packages/django/shortcuts.py", line 36, in render
content = loader.render_to_string(template_name, context, request, using=using)
File "/usr/local/lib/python3.6/dist-packages/django/template/loader.py", line 62, in render_to_string
return template.render(context, request)
File "/usr/local/lib/python3.6/dist-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)
File "/usr/local/lib/python3.6/dist-packages/django/template/base.py", line 169, in render
with context.bind_template(self):
File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
return next(self.gen)
File "/usr/local/lib/python3.6/dist-packages/django/template/context.py", line 246, in bind_template
updates.update(processor(self.request))
File "/usr/local/lib/python3.6/dist-packages/weblate/trans/context_processors.py", line 93, in weblate_context
if request.user.is_authenticated:
AttributeError: 'WSGIRequest' object has no attribute 'user'
```
</details>

**To Reproduce**
1. Grab the weblate/weblate:3.4-4 docker image
2. Configure it with environment `WEBLATE_ENABLE_HTTPS=1` and in settings-override.py:
```
SECURE_HSTS_SECONDS = 86400
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
```
3. Start a docker container

**Expected behavior**
Weblate starts normally

**Comment by nijel** [comment]
I can't reproduce this with pure Weblate, so most likely it is some issue in the Docker container. Moved the issue to docker repo because of that.
