### ISSUE TITLE
OperationalError: could not translate host name "database"

### ISSUE THREAD

**Issue by NLueg** [WeblateOrg/docker#1565]
### Describe the issue

Hi there! I get the following exception report, like once a week:

`OperationalError at /translate/pantrist/pantrist-app/pl/`
`could not translate host name "database" to address: Temporary failure in name resolution`

I first thought it's just a hiccup, but after this exception the docker-container consumes this much performance of the virtual server, that I have to restart it. Do you have any idea what the problem could be here? I looked like everywhere but don't found anything that could help.

Thank you very much in advance!

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Screenshots

![image](https://user-images.githubusercontent.com/48101693/181714275-0759d4cd-b20d-4906-a0b6-06d20e0cf616.png)

### Exception traceback

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

The above exception (could not translate host name "database" to address: Temporary failure in name resolution
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/weblate/accounts/middleware.py", line 57, in __call__
    request.user = user = get_user(request)
  File "/usr/local/lib/python3.10/site-packages/weblate/accounts/middleware.py", line 40, in get_user
    user = auth.get_user(request)
  File "/usr/local/lib/python3.10/site-packages/django/contrib/auth/__init__.py", line 198, in get_user
    user = backend.get_user(user_id)
  File "/usr/local/lib/python3.10/site-packages/social_core/backends/base.py", line 195, in get_user
    return self.strategy.get_user(user_id)
  File "/usr/local/lib/python3.10/site-packages/social_core/strategy.py", line 57, in get_user
    return self.storage.user.get_user(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/social_django/storage.py", line 97, in get_user
    return cls.user_model()._default_manager.get(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 492, in get
    num = len(clone)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 302, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1359, in execute_sql
    cursor = self.connection.cursor()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 260, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 243, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

During handling of the above exception (could not translate host name "database" to address: Temporary failure in name resolution
), another exception occurred:
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

The above exception (could not translate host name "database" to address: Temporary failure in name resolution
) was the direct cause of the following exception:
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/utils/deprecation.py", line 134, in __call__
    response = response or self.get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 57, in inner
    response = response_for_exception(request, exc)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 142, in response_for_exception
    log_response(
  File "/usr/local/lib/python3.10/site-packages/django/utils/log.py", line 241, in log_response
    getattr(logger, level)(
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1506, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/local/lib/python3.10/site-packages/django/utils/log.py", line 125, in emit
    reporter.get_traceback_text(),
  File "/usr/local/lib/python3.10/site-packages/django/views/debug.py", line 392, in get_traceback_text
    c = Context(self.get_traceback_data(), autoescape=False, use_l10n=False)
  File "/usr/local/lib/python3.10/site-packages/django/views/debug.py", line 354, in get_traceback_data
    self.filter.get_post_parameters(self.request).items()
  File "/usr/local/lib/python3.10/site-packages/weblate/trans/debug.py", line 40, in get_post_parameters
    for name, _url, version in get_versions_list():
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/requirements.py", line 225, in get_versions_list
    + get_db_cache_version()
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/requirements.py", line 213, in get_db_cache_version
    db_version = get_db_version()
  File "/usr/local/lib/python3.10/site-packages/weblate/utils/requirements.py", line 167, in get_db_version
    with connection.cursor() as cursor:
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 284, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 260, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 243, in ensure_connection
    with self.wrap_database_errors:
  File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 244, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/base/base.py", line 225, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 203, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

Exception Type: OperationalError at /translate/pantrist/pantrist-app/pl/
Exception Value: could not translate host name "database" to address: Temporary failure in name resolution
```

**Comment by nijel** [comment]
How do you run Weblate? Using provided docker-compose setup? Maybe https://docs.weblate.org/en/latest/admin/install/docker.html#envvar-POSTGRES_HOST is misconfigured...

**Comment by NLueg** [comment]
Hey @nijel! I run it as described in https://github.com/WeblateOrg/docker-compose.
I actually don't override the `POSTGRES_HOST` config. I have the following config in my `docker-compose.override.yml`:

```yaml
version: '3'
services:
  weblate:
    ports:
      - 1234:8080
    environment:
      WEBLATE_DEBUG: 0
      WEBLATE_ENABLE_HTTPS: 1
      WEBLATE_SERVER_EMAIL: xxx
      WEBLATE_DEFAULT_FROM_EMAIL: xxx
      WEBLATE_EMAIL_HOST: xxx      
      WEBLATE_EMAIL_HOST_USER: xxx
      WEBLATE_EMAIL_HOST_PASSWORD: xxx
      WEBLATE_SITE_DOMAIN: xxx
      WEBLATE_ADMIN_PASSWORD: xxx
      WEBLATE_ADMIN_NAME: xxx
      WEBLATE_ADMIN_EMAIL: xxx
      WEBLATE_GITHUB_USERNAME: weblate
      WEBLATE_GOOGLE_ANALYTICS_ID: xxx
      WEBLATE_CSP_CONNECT_SRC: xxx
```

**Comment by nijel** [comment]
That defines the `database` container - https://github.com/WeblateOrg/docker-compose/blob/a3b5beded55d806c1481d83ed31852873060ea79/docker-compose.yml#L15-L21.

Is it running?

**Comment by NLueg** [comment]
Sure, most of the time it works pretty good! But sometimes something leeds to the issue I mentioned above. This mostly happens when I delete a key.
But sometimes it also happens when one translator translations several keys. 

I really have no idea what could lead the issue, but I can't believe that I'm the only one ... I use like 1:1 the example for running Weblate with docker-compose besides the overrides I mentioned. There is no heavy trafic on the page either, currently only me and the translator.
At the beginning (when the translator translates many keys in short time) the issue happened like once a day.

I have 4 projects running on Weblate that all use JSON-files for currently 5 languages.

**Comment by nijel** [comment]
This really looks like some issue with the Docker or the database container. Maybe it is restarting for some reason?

**Comment by NLueg** [comment]
I can't tell, unfortunately. The only thing I can provide is the stacktrace I attached to the issue.
As the server is completely unusable in that case, I can't look into the container what exactly happened there.

**Comment by m3Lith** [comment]
@NLueg did you manage to figure out something more? I just started using Weblate via docker-compose, and bumped into very similar problems.

I'm running a fresh EC2 instance with Debian on it. Weblate installation completes without problems, then when I'm creating a component and it pulls translations from a remote repo, it would sometimes hang. Like completely hang the whole EC2 isntance - unable to even ssh into it (timeout). IF I restart it, it would work for some time until another more "intensive" action would be performed. And lately it even hangs by itself, without doing anything. The error that I get is the same:

```
OperationalError at /healthz
could not translate host name "database" to address: Temporary failure in name resolution
```

**Comment by NLueg** [comment]
Hey @m3Lith I can't tell actually ... After increasing the resources of the CentOS server everything works fine.
I didn't have any issue since than 🤷🏻‍♂️ This is not satisfying at all and I would really like to understand what the issue here is/was.

**Comment by m3Lith** [comment]
I see.. What specs did you use before, and to what did you increase?

**Comment by NLueg** [comment]
I went from `2 vCores` to `4 vCores` and from `4 GB` RAM to `8 GB` RAM.
But I of course have some other services running on it. So I don't think that Weblate always requires 8 GB RAM or something.

**Comment by nijel** [comment]
Let's followup at https://github.com/WeblateOrg/docker/issues/1719#issuecomment-1411911012
