### ISSUE TITLE
5.x image incompatibility with some kernels

### ISSUE THREAD

**Issue by steam3d** [WeblateOrg/docker#2096]
### Describe the issue

After upgrade, I can't run the Weblate. I got the error:
`weblate_1   | The /app/data volume is not writable, please adjust the permissions. Weblate is running as uid 1000`

I did not make any permissions changes. How to fix this?

### I already tried

- [X] I've read and searched [the documentation](https://docs.weblate.org/).
- [X] I've searched for similar issues in this repository.

### Steps to reproduce the behavior
```
# Fetch latest versions of the images
docker compose pull
# Stop and destroy the containers
docker compose down
# Spawn new containers in the background
docker compose up -d
# Follow the logs during upgrade
docker compose logs -f
```

### Screenshots

![image](https://github.com/WeblateOrg/weblate/assets/30986874/0a36b727-4493-4df4-b287-1378bff3f3d1)

### How do you run Weblate?

Docker container

**Comment by steam3d** [comment]
So should I try updating the system and then try updating the weblate?

**Comment by nijel** [comment]
Yes, that should help. I quickly tried to debug the issue back then, but I gave up, and I couldn't find anything related in the release notes. The volume is indeed not writable as a non-root user from the Debian 12 based containers, it's not just the test that would be wrong.

**Comment by steam3d** [comment]
I upgraded kernel to the latest one. Now I have such issue:

```
weblate_1   | Starting Weblate 5.3.1...
weblate_1   | System check identified no issues (1 silenced).
weblate_1   | Postgres 130013 is up
weblate_1   | Starting database migration...
weblate_1   | Operations to perform:
weblate_1   |   Apply all migrations: accounts, admin, auth, authtoken, configuration, contenttypes, django_celery_beat, gitexport, glossary, sessions, social_django, trans, utils, vcs, weblate_auth
weblate_1   | [2023-12-20 07:30:48,520: WARNING/74] Handled exception: KeyError: ('trans', 'change')
weblate_1   | Traceback (most recent call last):
weblate_1   |   File "/usr/local/bin/weblate", line 8, in <module>
weblate_1   |     sys.exit(main())
weblate_1   |              ^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/weblate/runner.py", line 19, in main
weblate_1   |     utility.execute()
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 436, in execute
weblate_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 412, in run_from_argv
weblate_1   |     self.execute(*args, **cmd_options)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 458, in execute
weblate_1   |     output = self.handle(*args, **options)
weblate_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 106, in wrapper
weblate_1   |     res = handle_func(*args, **kwargs)
weblate_1   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 301, in handle
weblate_1   |     pre_migrate_state = executor._create_project_state(with_applied_migrations=True)
weblate_1   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/executor.py", line 91, in _create_project_state
weblate_1   |     migration.mutate_state(state, preserve=False)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/migration.py", line 91, in mutate_state
weblate_1   |     operation.state_forwards(self.app_label, new_state)
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/operations/fields.py", line 93, in state_forwards
weblate_1   |     state.add_field(
weblate_1   |   File "/usr/local/lib/python3.11/site-packages/django/db/migrations/state.py", line 248, in add_field
weblate_1   |     self.models[model_key].fields[name] = field
weblate_1   |     ~~~~~~~~~~~^^^^^^^^^^^
weblate_1   | KeyError: ('trans', 'change')
weblate_1   |
weblate_1   | Database migration has failed. Please check the error message above.
weblate_1   | Note: Upgrading across major versions is not supported. In case you are upgrading
weblate_1   |       from an 4.x version, please upgrade to 5.0.2 first.
```

How to downgrade the docker-compose image to 5.0.2?

**Comment by steam3d** [comment]
I figure out. Full solution.

1. Upgrade kernel to the latest one:

```
sudo apt update && sudo apt -y upgrade
```


2. Add tag to `docker-compose.yml` weblate file

```
...
services:
	weblate:
	image: weblate/weblate:5.0.2.2
...
```

3. Upgrade weblate from 4.x to 5.0.2.2

```
docker-compose down
docker-compose pull
docker-compose up
```

4. Wait while migration complete. Check that everything works before go next.
5. Remove tag from  `docker-compose.yml` weblate file:

```
...
services:
	weblate:
	image: weblate/weblate
...
```


Upgrade weblate from 5.0.2.2 to the latest

```
docker-compose down
docker-compose pull
docker-compose up
```

**Comment by nijel** [comment]
https://github.com/docker-library/redis/issues/365#issuecomment-1599633849 might be the root cause here.

**Comment by licentiapoetica** [comment]
What I effectly did was to follow @steam3d's comment and then I updated my Debian 10 installation to Debian 11 which solved the volume not writable issue and I somehow ended up with weblate 5.5.5
