### ISSUE TITLE
Installation problems on docker

### ISSUE THREAD

**Issue by kiddingl** [WeblateOrg/docker#271]
This is some docker logs：

Postgres is up
sudo: unable to resolve host vm36
ERROR Handled exception NodeNotFoundError: b"Migration addons.0001_squashed_0006_addon_project_scope depends on nonexistent node ('trans', '0122_auto_20180129_1507'). Django tried to replace migration trans.0122_auto_20180129_1507 with any of [trans.0001_squashed_0143_auto_20180609_1655] but wasn't able to because some of the replaced migrations are already applied."
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 247, in build_graph
    self.graph.validate_consistency()
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/graph.py", line 243, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/graph.py", line 243, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/graph.py", line 96, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration addons.0001_squashed_0006_addon_project_scope dependencies reference nonexistent parent node ('trans', '0122_auto_20180129_1507')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/showmigrations.py", line 43, in handle
    return self.show_plan(connection, options['app_label'])
  File "/usr/local/lib/python3.5/dist-packages/django/core/management/commands/showmigrations.py", line 97, in show_plan
    loader = MigrationLoader(connection)
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/usr/local/lib/python3.5/dist-packages/django/db/migrations/loader.py", line 272, in build_graph
    ) from exc
django.db.migrations.exceptions.NodeNotFoundError: Migration addons.0001_squashed_0006_addon_project_scope depends on nonexistent node ('trans', '0122_auto_20180129_1507'). Django tried to replace migration trans.0122_auto_20180129_1507 with any of [trans.0001_squashed_0143_auto_20180609_1655] but wasn't able to because some of the replaced migrations are already applied.
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f58d3b48ea0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable
Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0x7f58d3b48ea0>
Traceback (most recent call last):
  File "/usr/lib/python3.5/weakref.py", line 117, in remove
TypeError: 'NoneType' object is not callable

----------------------
I can't deal with it.

**Comment by nijel** [comment]
Did this happen on upgrade? In case you were upgrading from 2.x release, you first should upgrade to 3.0 and then to newer 3.x release  (but the container should fail in this situation gracefully).

**Comment by kiddingl** [comment]
Because I just joined a company, this test server is down, so I am not sure if this is caused by an upgrade.
Now, I have a postgresql test database, I want to use it directly, how do I need to configure the weblate container to not have this problem?

**Comment by kiddingl** [comment]
I just want to use the data in the postgresql database. I don't know why there are migrations and applications. I don't know Django. Can you give me a detailed explanation?

**Comment by kiddingl** [comment]
Why do I need to migrate the database after installing weblate? What does this mean? I don't know much about how weblate works.

**Comment by nijel** [comment]
The migration needs to be done because you were previously running older version and the database schema was changed. First upgrade to `weblate:3.0.1-7`, start it up, it will migrate the schema and then you can upgrade to latest version.
