### ISSUE TITLE
Another weblate docker logs

### ISSUE THREAD

**Issue by kiddingl** [WeblateOrg/docker#276]
```
[root@vm36 ~]# docker run -d --name=weblate --env-file=webenv --network=host docker.io/weblate/weblate
1b6fa23dbbfb806a324883791acd34753ec2d676fa391c1851bb9bbbcb062e0f
[root@vm36 ~]# docker logs weblate
Postgres is up
sudo: unable to resolve host vm36: Name or service not known
sudo: unable to resolve host vm36: Name or service not known
[root@vm36 ~]# docker logs weblate
Postgres is up
sudo: unable to resolve host vm36: Name or service not known
sudo: unable to resolve host vm36: Name or service not known
ERROR Handled exception: IntegrityError: duplicate key value violates unique constraint "django_migrations_pkey"
DETAIL:  Key (id)=(271) already exists.

Operations to perform:
  Apply all migrations: accounts, addons, admin, auth, authtoken, checks, contenttypes, fonts, gitexport, lang, memory, screenshots, sessions, sites, social_django, trans, weblate_auth, wladmin
Running migrations:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "django_migrations_pkey"
DETAIL:  Key (id)=(271) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 34, in main
    execute_from_command_line(argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 234, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 246, in apply_migration
    self.record_migration(migration)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/executor.py", line 261, in record_migration
    self.recorder.record_applied(migration.app_label, migration.name)
  File "/usr/local/lib/python3.7/dist-packages/django/db/migrations/recorder.py", line 83, in record_applied
    self.migration_qs.create(app=app, name=name)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.7/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "django_migrations_pkey"
DETAIL:  Key (id)=(271) already exists.
```

-------------------------------------------
i can't deal with it

**Comment by nijel** [comment]
I'm a bit confused, this worked fine for you in https://github.com/WeblateOrg/docker/issues/275, so what are you doing now differently?

**Comment by kiddingl** [comment]
> I'm a bit confused, this worked fine for you in #275, so what are you doing now differently?

#275 weblate is running in k8s
#276 weblate is runnng in docker 
They use the same postgresql database

**Comment by kiddingl** [comment]
> I'm a bit confused, this worked fine for you in #275, so what are you doing now differently?

I want to solve some problems. 

1. WARNING/MainProcess] /usr/local/lib/python3.7/dist-packages/celery/fixups/django.py:202: UserWarning: Using settings.DEBUG leads to a memory leak, never use this setting in production environments!
2. ERROR/MainProcess] Process 'ForkPoolWorker-2' pid:198 exited with 'signal 9 (SIGKILL)'

**Comment by nijel** [comment]
Is it posible that they both *start* in same time? I don't think the Django migrations can deal with that and this is likely outcome - the both processes attempt to migrate the database at the same time.

Anyway to fix the first issue, just disable [WEBLATE_DEBUG](https://docs.weblate.org/en/latest/admin/deployments.html#envvar-WEBLATE_DEBUG).

For the SIGKILL have you checked container limits as suggested in https://github.com/WeblateOrg/docker/issues/275#issuecomment-506237676?

**Comment by kiddingl** [comment]
> Is it posible that they both _start_ in same time? I don't think the Django migrations can deal with that and this is likely outcome - the both processes attempt to migrate the database at the same time.
> 
> Anyway to fix the first issue, just disable [WEBLATE_DEBUG](https://docs.weblate.org/en/latest/admin/deployments.html#envvar-WEBLATE_DEBUG).
> 
> For the SIGKILL have you checked container limits as suggested in [#275 (comment)](https://github.com/WeblateOrg/docker/issues/275#issuecomment-506237676)?

Thank you, I solved the probem by increasing the memory and Disabled WBELATE_DEBUG.
Sorry,my English is  very poor.
