### ISSUE TITLE
cannot run container 3.7.1-7

### ISSUE THREAD

**Issue by mlaggner** [WeblateOrg/docker#326]
I've just started over a fresh install of weblate (on vmware virtual integrated containers) but I am not able to start the container. The following logs arise after the DB migrations have run:

```
Creating user admin
2019-08-05 07:32:59,470 INFO Included extra file "/etc/supervisor/conf.d/weblate.conf" during parsing
2019-08-05 07:32:59,490 INFO RPC interface 'supervisor' initialized
2019-08-05 07:32:59,491 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-08-05 07:32:59,492 INFO supervisord started with pid 302
2019-08-05 07:33:00,495 INFO spawnerr: unknown error making dispatchers for 'celery-notify': EACCES
2019-08-05 07:33:00,495 INFO spawnerr: unknown error making dispatchers for 'celery-memory': EACCES
2019-08-05 07:33:00,498 INFO spawnerr: unknown error making dispatchers for 'nginx': EACCES
2019-08-05 07:33:00,498 INFO spawnerr: unknown error making dispatchers for 'celery-beat': EACCES
2019-08-05 07:33:00,498 INFO spawnerr: unknown error making dispatchers for 'celery-search': EACCES
2019-08-05 07:33:00,499 INFO spawnerr: unknown error making dispatchers for 'celery-main': EACCES
2019-08-05 07:33:00,505 INFO spawnerr: unknown error making dispatchers for 'uwsgi': EACCES
2019-08-05 07:33:01,508 INFO spawnerr: unknown error making dispatchers for 'celery-notify': EACCES
2019-08-05 07:33:01,510 INFO spawnerr: unknown error making dispatchers for 'celery-memory': EACCES
2019-08-05 07:33:01,511 INFO spawnerr: unknown error making dispatchers for 'nginx': EACCES
2019-08-05 07:33:01,513 INFO spawnerr: unknown error making dispatchers for 'celery-beat': EACCES
2019-08-05 07:33:01,514 INFO spawnerr: unknown error making dispatchers for 'celery-search': EACCES
2019-08-05 07:33:01,516 INFO spawnerr: unknown error making dispatchers for 'celery-main': EACCES
2019-08-05 07:33:01,517 INFO spawnerr: unknown error making dispatchers for 'uwsgi': EACCES
2019-08-05 07:33:03,521 INFO spawnerr: unknown error making dispatchers for 'celery-notify': EACCES
2019-08-05 07:33:03,523 INFO spawnerr: unknown error making dispatchers for 'celery-memory': EACCES
2019-08-05 07:33:03,525 INFO spawnerr: unknown error making dispatchers for 'nginx': EACCES
2019-08-05 07:33:03,526 INFO spawnerr: unknown error making dispatchers for 'celery-beat': EACCES
2019-08-05 07:33:03,528 INFO spawnerr: unknown error making dispatchers for 'celery-search': EACCES
2019-08-05 07:33:03,529 INFO spawnerr: unknown error making dispatchers for 'celery-main': EACCES
2019-08-05 07:33:03,531 INFO spawnerr: unknown error making dispatchers for 'uwsgi': EACCES
2019-08-05 07:33:06,536 INFO spawnerr: unknown error making dispatchers for 'celery-notify': EACCES
2019-08-05 07:33:06,536 INFO gave up: celery-notify entered FATAL state, too many start retries too quickly
2019-08-05 07:33:06,539 INFO spawnerr: unknown error making dispatchers for 'celery-memory': EACCES
2019-08-05 07:33:06,539 INFO gave up: celery-memory entered FATAL state, too many start retries too quickly
2019-08-05 07:33:06,542 INFO spawnerr: unknown error making dispatchers for 'nginx': EACCES
2019-08-05 07:33:06,542 INFO gave up: nginx entered FATAL state, too many start retries too quickly
2019-08-05 07:33:06,545 INFO spawnerr: unknown error making dispatchers for 'celery-beat': EACCES
2019-08-05 07:33:06,546 INFO gave up: celery-beat entered FATAL state, too many start retries too quickly
2019-08-05 07:33:06,548 INFO spawnerr: unknown error making dispatchers for 'celery-search': EACCES
2019-08-05 07:33:06,549 INFO gave up: celery-search entered FATAL state, too many start retries too quickly
2019-08-05 07:33:06,551 INFO spawnerr: unknown error making dispatchers for 'celery-main': EACCES
2019-08-05 07:33:06,552 INFO gave up: celery-main entered FATAL state, too many start retries too quickly
2019-08-05 07:33:06,554 INFO spawnerr: unknown error making dispatchers for 'uwsgi': EACCES
2019-08-05 07:33:06,555 INFO gave up: uwsgi entered FATAL state, too many start retries too quickly
```

after a bit searching I found the thread at stackoverflow (https://stackoverflow.com/questions/35273197/unable-to-start-service-with-nohup-due-to-info-spawnerr-unknown-error-making-d) which looks like to be a regression of the switch from root to the user weblate

**Comment by nijel** [comment]
We don't open any log files in the supervisor (see https://github.com/WeblateOrg/docker/blob/master/etc/supervisor/conf.d/weblate.conf), so the cause is probably different. Any customizations in your setup?

**Comment by mlaggner** [comment]
only a settings-override.py for LDAP login..

but after logging into the docker container I saw the file `/etc/supervisor/supervisord.conf` with the following log contents:

```
[supervisord]
logfile=/var/log/supervisor/supervisord.log ; (main log file;default $CWD/supervisord.log)
pidfile=/var/run/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
childlogdir=/var/log/supervisor            ; ('AUTO' child log dir, default $TEMP)
```

could it be a problem that the supervisord daemon (which runs with pid 1000) is unable to write to `/var/log/supervisord/`?

**Comment by nijel** [comment]
That one is overridden on command line:

https://github.com/WeblateOrg/docker/blob/36604901e68136edd9f4200fa731596c2087ce38/start#L145

As I'm touching this file right now, I've removed these settings, but I doubt it will make any difference.

**Comment by mlaggner** [comment]
these changes did not work here..
nevertheless I've tried to run the same setup with the drocker image from 3.7.1-5 and that works OOB.

there must be some issue within the new rootless setup

**Comment by nijel** [comment]
How do you start the docker? What environment do you have set?

**Comment by mlaggner** [comment]
We use the vmware integrated container containers. But to set up the containers, we imported the docker-compose file (https://github.com/WeblateOrg/docker-compose/blob/4167a2237e8ef90a3c55bf6a042dc896edd4545f/docker-compose.yml) and slightly adopted this to make it useable by VIC:

```
version: '2'
services:
  weblate:
    image: weblate/weblate:3.7.1-5
    ports:
      - 80
    volumes:
      - weblate-data:/app/data
    links:
      - database
      - cache
    environment:
      - WEBLATE_DEBUG=0
      - WEBLATE_LOGLEVEL=DEBUG
      - WEBLATE_SITE_TITLE=Program Translation Tool
      - WEBLATE_ADMIN_NAME=Manuel Laggner
      - WEBLATE_ADMIN_EMAIL=manuel.laggner@gmail.com
      - WEBLATE_ADMIN_PASSWORD=1234567890asdfghjkl
      - WEBLATE_EMAIL=manuel.laggner@gmail.com
      - WEBLATE_SERVER_EMAIL=manuel.laggner@gmail.com
      - WEBLATE_DEFAULT_FROM_EMAIL=manuel.laggner@gmail.com
      - WEBLATE_ALLOWED_HOSTS=*
      - WEBLATE_REGISTRATION_OPEN=0
      - WEBLATE_TIME_ZONE=Europe/Vienna
      - POSTGRES_PASSWORD=weblate
      - POSTGRES_USER=weblate
      - POSTGRES_DATABASE=weblate
      - POSTGRES_HOST=database
      - POSTGRES_PORT=
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - WEBLATE_EMAIL_HOST=10.10.0.123 
      - WEBLATE_EMAIL_PORT=25
      - WEBLATE_EMAIL_USE_SSL=False
      - WEBLATE_EMAIL_USE_TLS=False
    restart: always
    depends_on:
      - database
      - cache

  database:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_PASSWORD=weblate
      - POSTGRES_USER=weblate
      - POSTGRES_DATABASE=weblate
      - POSTGRES_HOST=database
      - POSTGRES_PORT=
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  cache:
    image: redis:4-alpine
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
volumes:
  weblate-data: {}
  postgres-data: {}
  redis-data: {}
```

this docker-compose.yml works with 3.7.1-5 but not with 3.7.1-7

**Comment by nijel** [comment]
I don't see anything suspicious there. What won't work is the port as it has changed, see https://weblate.org/news/archive/weblate-docker-container-changes/

**Comment by mlaggner** [comment]
thanks for the hint - we've definitely the wrong port, but it is still not starting here :(

**Comment by nijel** [comment]
I didn't expect it would fix that, it's just issue you would hit later :-).

Back to the original issue - unfortunately the supervisor is not really helpful in providing *what* has failed. Are you able to manually patch the container so that it raises the actual error instead of hiding it? Just replace `return` by `raise` on https://github.com/Supervisor/supervisor/blob/dbff619f79c48da0776178e627221da6e40a3261/supervisor/process.py#L239

**Comment by mlaggner** [comment]
```
Creating user admin
2019-08-05 14:01:41,244 INFO Included extra file "/etc/supervisor/conf.d/weblate.conf" during parsing
2019-08-05 14:01:41,277 INFO RPC interface 'supervisor' initialized
2019-08-05 14:01:41,279 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2019-08-05 14:01:41,280 INFO supervisord started with pid 304
2019-08-05 14:01:42,282 INFO spawnerr: unknown error making dispatchers for 'celery-notify': EACCES
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 11, in <module>
    load_entry_point('supervisor==3.3.5', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 361, in main
    go(options)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 371, in go
    d.main()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 77, in main
    self.run()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 94, in run
    self.runforever()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 245, in runforever
    group.transition()
  File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 764, in transition
    proc.transition()
  File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 605, in transition
    self.spawn()
  File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 219, in spawn
    self.dispatchers, self.pipes = self.config.make_dispatchers(self)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1828, in make_dispatchers
    dispatchers[stdout_fd] = POutputDispatcher(proc, etype, stdout_fd)
  File "/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py", line 99, in __init__
    backups=backups)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 456, in getLogger
    backups, stdout)
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 344, in getLogger
    handlers.append(FileHandler(filename))
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 13] Permission denied: '/dev/stdout'
```

**Comment by mlaggner** [comment]
maybe the hint from https://github.com/moby/moby/issues/31243#issuecomment-406879017 could solve this issue?

modify the line https://github.com/WeblateOrg/docker/blob/463bf9b2088cabeff59d700ca2425c580245d9e6/Dockerfile#L13 and add `tty`

**Comment by nijel** [comment]
I've just done that, I'm curious if that will really help you.

**Comment by mlaggner** [comment]
I can test this as soon as there is a new version on dockerhub

**Comment by nijel** [comment]
You can use the edge tag right now.

**Comment by mlaggner** [comment]
I've tried the edge build of the docker container, but unfortunately it is not working. I still get the same error (with the patched process.py):

```
2019-08-06 08:08:29,091 INFO supervisord started with pid 306
2019-08-06 08:08:30,094 INFO spawnerr: unknown error making dispatchers for 'celery-notify': EACCES
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 11, in <module>
    load_entry_point('supervisor==3.3.5', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 361, in main
    go(options)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 371, in go
    d.main()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 77, in main
    self.run()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 94, in run
    self.runforever()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 245, in runforever
    group.transition()
  File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 764, in transition
    proc.transition()
  File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 605, in transition
    self.spawn()
  File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 219, in spawn
    self.dispatchers, self.pipes = self.config.make_dispatchers(self)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1828, in make_dispatchers
    dispatchers[stdout_fd] = POutputDispatcher(proc, etype, stdout_fd)
  File "/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py", line 99, in __init__
    backups=backups)
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 456, in getLogger
    backups, stdout)
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 344, in getLogger
    handlers.append(FileHandler(filename))
  File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 98, in __init__
    self.stream = open(filename, mode)
IOError: [Errno 13] Permission denied: '/dev/stdout'
```

inside the container I can change to the user weblate and write directly to /dev/stdout.. I have no clue, why supervisord is not working here..

**Comment by nijel** [comment]
It certainly has something to do with the vmware stuff you're using. The current container works fine in normal Docker and OpenShift.

Can you check what file and permissions are on /proc/self/fd/1?

**Comment by nijel** [comment]
What might be alternative solution is https://stackoverflow.com/a/21371113/225718

**Comment by nijel** [comment]
I've tried to implement this in https://github.com/WeblateOrg/docker/pull/328

**Comment by mlaggner** [comment]
sorry, did not work :(

when I enter the docker instance as root:

```
/# ls -Flah /dev/stdout
lrwxrwxrwx 1 root root 15 Aug  7 07:17 /dev/stdout -> /proc/self/fd/1

/# ls -Flah /proc/self/fd/1
lrwx------ 1 root root 64 Aug  7 07:22 /proc/self/fd/1 -> /dev/pts/0

/# ls -Flah /dev/pts/0
crw--w---- 1 root tty 136, 0 Aug  7 07:22 /dev/pts/0
```

when I enter the docker instance as weblate:

```
/$ ls -Flah /dev/stdout
lrwxrwxrwx 1 root root 15 Aug  7 07:17 /dev/stdout -> /proc/self/fd/1

/$ ls -Flah /proc/self/fd/1
lrwx------ 1 weblate weblate 64 Aug  7 07:26 /proc/self/fd/1 -> /dev/pts/2

/$ ls -Flah /dev/pts/2
crw--w---- 1 root tty 136, 2 Aug  7 07:26 /dev/pts/2
```

I may patch the `start` file to get the exact values just before supervisord starts

**Comment by mlaggner** [comment]
here are the results from the start script:

```
lrwxrwxrwx 1 root root 15 Aug  7 07:37 /dev/stdout -> /proc/self/fd/1|
l-wx------ 1 weblate weblate 64 Aug  7 07:38 /proc/self/fd/1 -> pipe:[3715]
```

looks like this is the non-TTY part from moby/moby#31243 (comment):

>Non-TTY
None of these solutions work.
Instead of /dev/pts, /proc/self/fd 0-2 are pipes that you can't chmod or chown, and have no group permissions allowed. Again, this is how linux works, and is not technically a docker bug.
I don't how the permissions of these pipes are derived, or where a workaround similar to option 3 could be added.

but the solution is in the same issue 👍 -> https://github.com/moby/moby/issues/31243#issuecomment-406825071

appending `-t ` when starting the docker instance via docker run (or `tty: true` in docker-compose) looks like to solve the issue!

thanks for your patience

**Comment by nijel** [comment]
I think changes from https://github.com/WeblateOrg/docker/pull/328 could address it as well, I've just pushed it to `edge` (it usually takes about 30 minutes until the update is available on the Docker Hub), so it would be great if you could test that as well (without -t).

**Comment by mlaggner** [comment]
can confirm: the latest edge build is starting now:

```
Creating user admin
2019-08-07 09:17:18,991 INFO Included extra file "/etc/supervisor/conf.d/weblate.conf" during parsing
2019-08-07 09:17:19,016 INFO RPC interface 'supervisor' initialized
2019-08-07 09:17:19,017 INFO supervisord started with pid 313
2019-08-07 09:17:20,020 INFO spawned: 'stdout' with pid 415
2019-08-07 09:17:20,023 INFO spawned: 'celery-memory' with pid 416
2019-08-07 09:17:20,025 INFO spawned: 'celery-notify' with pid 417
2019-08-07 09:17:20,026 INFO spawned: 'celery-beat' with pid 418
2019-08-07 09:17:20,028 INFO spawned: 'celery-search' with pid 419
2019-08-07 09:17:20,029 INFO spawned: 'celery-main' with pid 420
2019-08-07 09:17:20,045 INFO spawned: 'nginx' with pid 421
2019-08-07 09:17:20,066 INFO spawned: 'uwsgi' with pid 423
2019-08-07 09:17:21,398 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-07 09:17:21,400 INFO success: celery-memory entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-07 09:17:21,400 INFO success: celery-notify entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-07 09:17:21,400 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-07 09:17:21,400 INFO success: celery-search entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-07 09:17:21,408 INFO success: celery-main entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-07 09:17:21,408 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2019-08-07 09:17:21,408 INFO success: uwsgi entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

**Comment by nijel** [comment]
Great, thanks for testing.
