### ISSUE TITLE
Deploy Weblate in Azure Kubernetes

### ISSUE THREAD

**Issue by nunorcenteio** [WeblateOrg/docker#949]
Hi,

I've evaluating Weblate and for that I want to deploy an instance on my Azure Kubernetes.
I've installed in using the following command:

helm install my-release weblate/weblate --set service.type="LoadBalancer" --set siteDomain="xxx.domain.com" --namespace weblate

Everything is running but after a while my weblate pod crashes. In the logs I have this:

```pytb
Traceback (most recent call last):
  File "/usr/local/bin/weblate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/weblate/runner.py", line 34, in main
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/shell.py", line 87, in handle
    exec(options['command'])
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/django_redis/cache.py", line 34, in _decorator
    raise e.__cause__
  File "/usr/local/lib/python3.7/dist-packages/django_redis/client/default.py", line 509, in has_key
    return client.exists(key) == 1
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 1581, in exists
    return self.execute_command('EXISTS', *names)
  File "/usr/local/lib/python3.7/dist-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.7/dist-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to my-release-weblate-redis-master:6379. Name or service not known.
```

These are my services:
![image](https://user-images.githubusercontent.com/7903120/106793694-afa1d400-664f-11eb-9cea-d240b712fc0e.png)

Any hint?

Thanks

**Comment by nijel** [comment]
It was probably just waiting for redis to be available, and then it gave up (it should be visible in the log before this error).

My Kubernetes experience is zero, but seems like networking or resolver issue - Weblate container cannot resolve "my-release-weblate-redis-master".

**Comment by nunorcenteio** [comment]
Yep, seems something wrong with the helm deploy file. The redis service created is named "my-release-redis-master" and not "my-release-weblate-redis-master".
I had to pass --set redis.redisHost="my-release-redis-master" --set postgresql.postgresqlHost="my-release-postgresql" to helm install
